# Generated by Django 4.0.4 on 2022-09-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='about/', verbose_name='Image')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/%y/%m/%d/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='banner/%y/%m/%d/', verbose_name='Banner')),
                ('card', models.ImageField(upload_to='card/%y/%m/%d/', verbose_name='Card')),
                ('title', models.CharField(max_length=255, verbose_name='Name of Tour')),
                ('slug', models.SlugField(unique=True)),
                ('cost', models.CharField(max_length=200, verbose_name='Cost')),
                ('rating', models.IntegerField(default=5, verbose_name='Star')),
                ('description', models.TextField()),
                ('about', models.ManyToManyField(blank=True, to='main.abouttour')),
                ('gallery', models.ManyToManyField(blank=True, to='main.gallery')),
            ],
        ),
    ]
