# Generated by Django 4.0.4 on 2022-10-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='cost_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Cost'),
        ),
        migrations.AddField(
            model_name='tour',
            name='cost_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Cost'),
        ),
        migrations.AddField(
            model_name='tour',
            name='cost_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Cost'),
        ),
        migrations.AddField(
            model_name='tour',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name of Tour'),
        ),
        migrations.AddField(
            model_name='tour',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Name of Tour'),
        ),
        migrations.AddField(
            model_name='tour',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Name of Tour'),
        ),
    ]
