# Generated by Django 4.0.4 on 2022-10-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_contact_phone_alter_contact_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
